services:
  - type: web
    name: audit-assistant
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn audit_assistant.app:app --worker-tmp-dir /dev/shm
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: audit_assistant/app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: 3a359880a6ca37316e5e9565d7f731f89e676a0c3956a286
    plan: free